# Generated by Django 4.2.4 on 2023-08-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='access',
            field=models.IntegerField(choices=[(0, 'seller'), (1, 'customer')], default=1),
        ),
    ]
