# Generated by Django 4.2.4 on 2024-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="store_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
