# Generated by Django 4.2.4 on 2023-08-26 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('store_name', models.CharField(max_length=20)),
                ('store_type', models.IntegerField(choices=[(1, 'لوازم خانگی'), (2, 'لبنیات'), (3, 'شیرینی فروشی'), (4, 'لوازم الکترونیک'), (5, 'سوپر مارکت')])),
            ],
        ),
    ]
