# Generated by Django 4.2.4 on 2023-08-24 09:55

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Accounts', '0002_alter_User_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='User',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelManagers(
            name='User',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='User',
            name='User_name',
        ),
        migrations.AddField(
            model_name='User',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='User',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this User belongs to. A User will get all permissions granted to each of their groups.', related_name='User_set', related_query_name='User', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='User',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this User should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='User',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the User can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='User',
            name='is_superUser',
            field=models.BooleanField(default=False, help_text='Designates that this User has all permissions without explicitly assigning them.', verbose_name='superUser status'),
        ),
        migrations.AddField(
            model_name='User',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='User',
            name='User_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this User.', related_name='User_set', related_query_name='User', to='auth.permission', verbose_name='User permissions'),
        ),
        migrations.AddField(
            model_name='User',
            name='Username',
            field=models.CharField(default=1, error_messages={'unique': 'A User with that Username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='User',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='User',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='User',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='User',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
