# Generated by Django 4.2.4 on 2023-08-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_seller_user'),
        ('Accounts', '0006_seller_id_alter_seller_user'),
    ]

    operations = [
    ]
