# Generated by Django 4.2.4 on 2023-08-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0001_initial'),
        ('Accounts', '0008_customer_id_alter_customer_user_alter_seller_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('productDelivery', models.IntegerField(choices=[(0, 'Normal delivery'), (1, 'Special delivery')])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
    ]
