# Generated by Django 4.2.4 on 2023-08-30 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_customer_id_alter_customer_user_alter_seller_user'),
        ('customer', '0002_remove_cart_productdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seller',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer'),
            preserve_default=False,
        ),
    ]
