# Generated by Django 4.2.4 on 2023-08-31 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_customer_id_alter_customer_user_alter_seller_user'),
        ('Seller', '0001_initial'),
        ('customer', '0003_remove_cart_seller_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='number',
            new_name='quantity',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
    ]
