# Generated by Django 4.2.4 on 2023-10-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
                ('referenceCategory', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='childCategories', to='Seller.category')),
            ],
        ),
        migrations.CreateModel(
            name='staticFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(max_length=20)),
                ('category', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Seller.category')),
                ('describedFeatures', models.ManyToManyField(to='Seller.staticfeature')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('product_quantity', models.IntegerField(choices=[(0, 'تعدادی'), (1, 'کیلویی')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='intDynamicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureNumber', models.IntegerField()),
                ('baseFeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.staticfeature')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intD', to='Seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDynamicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureImage', models.CharField(max_length=20)),
                ('baseFeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.staticfeature')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgD', to='Seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='charDynamicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(max_length=20)),
                ('baseFeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.staticfeature')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charD', to='Seller.product')),
            ],
        ),
    ]
