# Generated by Django 4.2.4 on 2023-08-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0004_remove_customer_id_remove_seller_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('product_quantity', models.IntegerField(choices=[(0, 'تعدادی'), (1, 'کیلویی')])),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='productField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=20)),
                ('fieldValue', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
            ],
        ),
    ]
