# Generated by Django 4.2.7 on 2023-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfeature',
            name='describedFeatures',
            field=models.ManyToManyField(related_name='describerFeatures', to='Seller.staticfeature'),
        ),
    ]
