# Generated by Django 4.2.4 on 2023-09-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldValue', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='fieldValue',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='product',
        ),
        migrations.CreateModel(
            name='productDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
                ('productValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.productvalue')),
                ('productfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.productfield')),
            ],
        ),
    ]
