# Generated by Django 4.2.4 on 2023-10-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='referenceCategory',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Seller.category'),
        ),
        migrations.AlterField(
            model_name='chardynamicfeature',
            name='products',
            field=models.ManyToManyField(null=b'I01\n', to='Seller.product'),
        ),
        migrations.AlterField(
            model_name='imagedynamicfeature',
            name='products',
            field=models.ManyToManyField(null=b'I01\n', to='Seller.product'),
        ),
        migrations.AlterField(
            model_name='intdynamicfeature',
            name='products',
            field=models.ManyToManyField(null=b'I01\n', to='Seller.product'),
        ),
        migrations.AlterField(
            model_name='staticfeature',
            name='category',
            field=models.ManyToManyField(null=b'I01\n', to='Seller.category'),
        ),
        migrations.AlterField(
            model_name='staticfeature',
            name='feature',
            field=models.ManyToManyField(null=b'I01\n', to='Seller.staticfeature'),
        ),
    ]
