# Generated by Django 4.2.4 on 2023-10-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_category_referencecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticfeature',
            name='features',
        ),
        migrations.AddField(
            model_name='staticfeature',
            name='describedFeatures',
            field=models.ManyToManyField(related_name='describerFeatures', to='Seller.staticfeature'),
        ),
        migrations.AlterField(
            model_name='category',
            name='referenceCategory',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='childCategories', to='Seller.category'),
        ),
    ]
