# Generated by Django 4.2.4 on 2023-09-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_productvalue_remove_productfield_fieldvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='charDynamicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageDynamicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureImage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='intDynamicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staticFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(max_length=20)),
                ('childfeatures', models.ManyToManyField(to='Seller.staticfeature')),
                ('products', models.ManyToManyField(to='Seller.product')),
            ],
        ),
        migrations.DeleteModel(
            name='productDetail',
        ),
        migrations.DeleteModel(
            name='productField',
        ),
        migrations.DeleteModel(
            name='productValue',
        ),
        migrations.AddField(
            model_name='intdynamicfeature',
            name='baseFeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.staticfeature'),
        ),
        migrations.AddField(
            model_name='intdynamicfeature',
            name='products',
            field=models.ManyToManyField(to='Seller.product'),
        ),
        migrations.AddField(
            model_name='imagedynamicfeature',
            name='baseFeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.staticfeature'),
        ),
        migrations.AddField(
            model_name='imagedynamicfeature',
            name='products',
            field=models.ManyToManyField(to='Seller.product'),
        ),
        migrations.AddField(
            model_name='chardynamicfeature',
            name='baseFeature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.staticfeature'),
        ),
        migrations.AddField(
            model_name='chardynamicfeature',
            name='products',
            field=models.ManyToManyField(to='Seller.product'),
        ),
    ]
