# Generated by Django 4.2.4 on 2023-09-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_chardynamicfeature_imagedynamicfeature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staticfeature',
            name='childfeatures',
        ),
        migrations.RemoveField(
            model_name='staticfeature',
            name='products',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
                ('referenceCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticfeature',
            name='categoryName',
            field=models.ManyToManyField(to='Seller.category'),
        ),
    ]
