# Generated by Django 4.2.5 on 2023-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_remove_staticfeature_category_staticfeature_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticfeature',
            name='feature',
        ),
        migrations.AddField(
            model_name='staticfeature',
            name='features',
            field=models.ManyToManyField(to='Seller.staticfeature'),
        ),
        migrations.AlterField(
            model_name='chardynamicfeature',
            name='products',
            field=models.ManyToManyField(to='Seller.product'),
        ),
        migrations.AlterField(
            model_name='imagedynamicfeature',
            name='products',
            field=models.ManyToManyField(to='Seller.product'),
        ),
        migrations.AlterField(
            model_name='intdynamicfeature',
            name='products',
            field=models.ManyToManyField(to='Seller.product'),
        ),
    ]
