# Generated by Django 4.2.4 on 2023-10-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_remove_staticfeature_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfeature',
            name='describedFeatures',
            field=models.ManyToManyField(to='Seller.staticfeature'),
        ),
    ]
