# Generated by Django 4.2.4 on 2023-09-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticfeature',
            old_name='categoryName',
            new_name='category',
        ),
    ]
