# Generated by Django 4.2.4 on 2023-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_rename_categoryname_staticfeature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfeature',
            name='feature',
            field=models.ManyToManyField(to='Seller.staticfeature'),
        ),
    ]
